//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrialTable
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public string ModifiedData { get; set; }
        public string OriginalData { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
