//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundingRequestTable
    {
        public System.Guid Id { get; set; }
        public string Userid { get; set; }
        public Nullable<System.Guid> SystemAccount { get; set; }
        public string PaymentStatus { get; set; }
        public string Reason { get; set; }
        public string TransactionNarration { get; set; }
        public string PaymentType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SystemAccountTable SystemAccountTable { get; set; }
    }
}
