//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTable
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public string Path { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
