//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTable()
        {
            this.ItemsTables = new HashSet<ItemsTable>();
        }
    
        public System.Guid Id { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string OrderType { get; set; }
        public Nullable<decimal> TotalServiceCharge { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsActive { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string TrackingNumber { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsTable> ItemsTables { get; set; }
    }
}
