//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTable()
        {
            this.ImageTables = new HashSet<ImageTable>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProductTypeId { get; set; }
        public string ProductLink { get; set; }
        public Nullable<System.Guid> VendorId { get; set; }
        public string SellerPhoneNumber { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<decimal> ItemsPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual DomesticOrderTable DomesticOrderTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageTable> ImageTables { get; set; }
        public virtual VendorTable VendorTable { get; set; }
        public virtual ShippingOrderTable ShippingOrderTable { get; set; }
    }
}
