//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingTable
    {
        public System.Guid Id { get; set; }
        public string paystackSecretKey { get; set; }
        public string paystackPublicKey { get; set; }
        public string SmSUsername { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
    }
}
