//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingChargeTable
    {
        public System.Guid Id { get; set; }
        public decimal MinQuantity { get; set; }
        public decimal MaxQuantity { get; set; }
        public decimal Price { get; set; }
        public string Type { get; set; }
        public string OriginCountry { get; set; }
        public string DestinationCountry { get; set; }
        public bool IsActive { get; set; }
    }
}
