//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasudaDataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VasudaModel : DbContext
    {
        public VasudaModel()
            : base("name=VasudaModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuditTrialTable> AuditTrialTables { get; set; }
        public virtual DbSet<BankTable> BankTables { get; set; }
        public virtual DbSet<CategoryTable> CategoryTables { get; set; }
        public virtual DbSet<ChatTable> ChatTables { get; set; }
        public virtual DbSet<ContactTable> ContactTables { get; set; }
        public virtual DbSet<ExchangeRateTable> ExchangeRateTables { get; set; }
        public virtual DbSet<FundingRequestTable> FundingRequestTables { get; set; }
        public virtual DbSet<ImageTable> ImageTables { get; set; }
        public virtual DbSet<NotificationTable> NotificationTables { get; set; }
        public virtual DbSet<OrderTable> OrderTables { get; set; }
        public virtual DbSet<PaymentHistoryTable> PaymentHistoryTables { get; set; }
        public virtual DbSet<PriceTable> PriceTables { get; set; }
        public virtual DbSet<ProductTable> ProductTables { get; set; }
        public virtual DbSet<SettingTable> SettingTables { get; set; }
        public virtual DbSet<SubCategoryTable> SubCategoryTables { get; set; }
        public virtual DbSet<SupportTable> SupportTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemAccountTable> SystemAccountTables { get; set; }
        public virtual DbSet<VendorTable> VendorTables { get; set; }
        public virtual DbSet<WithdrawalDetailsTable> WithdrawalDetailsTables { get; set; }
        public virtual DbSet<WithdrawalRequestTable> WithdrawalRequestTables { get; set; }
    }
}
